### PR TITLE
fix: Add better logging for command not found errors

### LINKED ISSUE #297: Gracefully exit with a nice error if we can't find the passed command
It's not uncommon for folks to reach out to support with an error that looks like: `Error: spawn cypress ENOENT`

This is usually because the passed command to `percy exec --` can't be found. We should capture this error and show a nice error message that says the command can't be found. Maybe link to a doc nudging the user to create a script in their `package.json` so the binary can be found.

### PR DESCRIPTION
**Pull request by wwilsman**
## Purpose

We started noticing `[percy] undefined` in the logs whenever the command being executed was not found in the $PATH. This was due to the error object being passed through from the child's `error` handler being interpreted incorrectly by Winston 3.x. Winston attempts to find a `msg` property on the passed object, which is where `undefined` was coming from. Winston does have logic for handling Error instances, but for some reason the error provided by cross-spawn did not get handled like a normal Error.

Fixes #297 

## Approach

Call `.toString()` on the error to log the error message rather than the error object.

The error this produced was `spawn foobar ENOENT` which might not be obvious to some that it means the command was not found. So I utilized a transitive dependency `which` to perform a cross-platform check for the provided command so we can log a much friendlier error.

In addition, I added a non-zero exit code to the missing command logic and tested that as well.

### CODE REVIEW

File: src/commands/exec.ts [hunk 1]
```diff
@@ -1,5 +1,6 @@
 import { flags } from '@oclif/command'
 import * as spawn from 'cross-spawn'
+import * as which from 'which'
```
Comment (Robdel12) [inline src/commands/exec.ts]: Do you know if this is cross platform safe? I couldn't see anything that says yay or nay on the packages npm page

File: test/acceptance/exec.test.js [hunk 2]
```diff
@@ -18,6 +18,26 @@ describe('percy exec', () => {
...
+      '[percy] Example:',
+      '[percy] $ percy exec -- echo "run your test suite"'
+    ])
+  })
+
+  it('errors when the command cannot be found', async () => {
+    let [stdout, stderr, code] = await run('percy exec -- foobar')
+
+    expect(code).toEqual(127)
+    expect(stderr).toHaveEntry('[percy] Error: command not found "foobar"')
```
Comment (Robdel12) [inline test/acceptance/exec.test.js]: I LOVE these tests hahaha

File: src/commands/exec.ts (hunk 1 above)
Comment (Robdel12) [reply src/commands/exec.ts]: https://github.com/npm/node-which/blob/8ef60698398872699b5446a06fc579d281a94b91/which.js#L6 looks like it does.

Totally want to verify this on a windows machine before though 😬

Comment (wwilsman) [reply src/commands/exec.ts]: It's a dependency of cross-spawn, so it is verified to work on a windows machine 🙂

Comment (wwilsman) [reply src/commands/exec.ts]: I initially used `spawn.sync('which', [command])` but added the dep for winders

Comment (wwilsman) [reply src/commands/exec.ts]: Also from the PR description 😜 

> So I utilized a transitive dependency which to perform a cross-platform check
